wiremock/WireMock.Net

src/WireMock.Net/Admin/Mappings/EncodingModel.cs
src/WireMock.Net/Admin/Mappings/ResponseModel.cs
src/WireMock.Net/Admin/Requests/LogRequestModel.cs
src/WireMock.Net/Admin/Requests/LogResponseModel.cs
src/WireMock.Net/HttpListenerRequestMapper.cs
src/WireMock.Net/HttpListenerResponseMapper.cs
src/WireMock.Net/RequestMessage.cs
src/WireMock.Net/ResponseBuilders/IBodyResponseBuilder.cs
src/WireMock.Net/ResponseBuilders/Response.cs
src/WireMock.Net/ResponseMessage.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
test/WireMock.Net.Tests/HttpListenerResponseMapperTests.cs
test/WireMock.Net.Tests/RequestMessageTests.cs
test/WireMock.Net.Tests/RequestTests.cs
test/WireMock.Net.Tests/ResponseTests.cs

Support custom body encoding instead default utf8

Body Encoding

---

examples/WireMock.Net.Console.Record.NETCoreApp/Program.cs
examples/WireMock.Net.ConsoleApplication/MainApp.cs
src/WireMock.Net.StandAlone/StandAloneApp.cs
src/WireMock.Net/Admin/Mappings/ResponseModel.cs
src/WireMock.Net/Http/CertificateUtil.cs
src/WireMock.Net/Http/HttpClientHelper.cs
src/WireMock.Net/ResponseBuilders/IProxyResponseBuilder.cs
src/WireMock.Net/ResponseBuilders/Response.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
test/WireMock.Net.Tests/FluentMockServerTests.cs

Add support for client certificate password and test with real services that require client certificates. Also update so when proxying, the path and query will be passed to the proxied api.
Please have a look and let me know what you think. I ran a test for it locally, but it's a bit hard to checkin a runnable unit test as it would require a real service (which I have in my environment) plus a valid pfx with password

[Feature] Add support for client certificate password and test with real services that require client certificate auth

---

src/WireMock.Net/Http/HttpClientHelper.cs

Proxy didn't process some headers correctly.
1. `Content-*` headers can't be set manually with validation
2. Valid AWS `Authorization-*` header required validation
Reproduce:
1. Create Wiremock instance
2. Start local DynamoDb
3. Proxy all requests to DynamoDb
4. Create any request with DynamoDb API

Fix the problem with headers passthrough

---

examples/WireMock.Net.Console.NETCoreApp/__admin/mappings/11111110-a633-40e8-a244-5cb80bc0ab66.json
examples/WireMock.Net.ConsoleApplication/MainApp.cs
src/WireMock.Net/Admin/Mappings/ResponseModel.cs
src/WireMock.Net/Admin/Requests/LogRequestModel.cs
src/WireMock.Net/Admin/Requests/LogResponseModel.cs
src/WireMock.Net/Http/HttpClientHelper.cs
src/WireMock.Net/Matchers/Request/RequestMessageHeaderMatcher.cs
src/WireMock.Net/Owin/OwinRequestMapper.cs
src/WireMock.Net/Owin/OwinResponseMapper.cs
src/WireMock.Net/Owin/WireMockMiddleware.cs
src/WireMock.Net/RequestBuilders/IHeadersAndCookiesRequestBuilder.cs
src/WireMock.Net/RequestBuilders/Request.cs
src/WireMock.Net/RequestMessage.cs
src/WireMock.Net/ResponseBuilders/IHeadersResponseBuilder.cs
src/WireMock.Net/ResponseBuilders/Response.cs
src/WireMock.Net/ResponseMessage.cs
src/WireMock.Net/Serialization/MappingConverter.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
src/WireMock.Net/Transformers/ResponseMessageTransformer.cs
src/WireMock.Net/Util/JsonUtils.cs
src/WireMock.Net/Util/WireMockList.cs
test/WireMock.Net.Tests/RequestMessageTests.cs
test/WireMock.Net.Tests/RequestTests.ClientIP.cs
test/WireMock.Net.Tests/RequestTests.cs
test/WireMock.Net.Tests/ResponseTests.Handlebars.cs
test/WireMock.Net.Tests/ResponseTests.cs
test/WireMock.Net.Tests/StatefulBehaviorTests.cs

Add ability to specify several values for same header in response. In this PR it is not supported to define in json.
WithHeader and WithHeaders methods are backward-compatible. The only change, that could be breaking - public property Headers in ResponseMessage has different type now

Add ability to provide multiple values for headers in response

---

appveyor.yml
src/WireMock.Net/RequestMessage.cs
test/WireMock.Net.Tests/ResponseTests.Handlebars.cs

Hi
I needed to be able to template responses based on more granular information than was already available in the request object so have added some calculated fields and supporting test. Would you be interested in accepting it back?
- Add new fields for Host, Origin, protocol and Port during request message creation, derived from the Uri object
- Allow the new fields to be accessed in the templating engine
- Add tests for the new fields

Add the Host, Protocol, Port and Origin to the Request message so they can be used in templating

---

src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
src/WireMock.Net/Owin/GlobalExceptionMiddleware.cs
src/WireMock.Net/Owin/OwinSelfHost.cs
src/WireMock.Net/Owin/WireMockMiddleware.cs
src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
src/WireMock.Net/Util/ConcurentObservableCollection.cs
test/WireMock.Net.Tests/ObservableLogEntriesTest.cs

Fixed issue with concurrent logging:
* added `ConcurrentObservableCollection` which is thread safe
* added test for checking logging with parallel requests
* added `GlobalExceptionMiddleware` that handles all exceptions that can happen in next middlewares
* changed response body from exception message to serialized exception when exception is thrown(it`s better to have whole exception fields than only exception message)

Fix issue with concurrent logging

---

README.md
src/WireMock.Net/Client/IFluentMockServerAdmin.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
test/WireMock.Net.Tests/FluentMockServerAdminRestClientTests.cs

Hello. Been testing the use of the admin api client with RestEase and noticed that the definition has the wrong types listed as being return on the get requests API meaning the restease client has null values and some data is missing. In addition the find requests API does not return LogEntryModel like the GetRequests API instead it returns LogEntry, which I have fixed so they are all the same.
- IFluentMockServerAdmin get, find and get all requests should return a log entry model
- Add tests for get and find using the rest ease api client

bug: Fix admin api client definition returning the wrong types

---

src/WireMock.Net/Client/IFluentMockServerAdmin.cs
src/WireMock.Net/Owin/OwinRequestMapper.cs
src/WireMock.Net/RequestBuilders/IMethodRequestBuilder.cs
src/WireMock.Net/RequestBuilders/Request.cs
test/WireMock.Net.Tests/FluentMockServerTests.cs
test/WireMock.Net.Tests/RequestTests.PathAndMethod.cs
test/WireMock.Net.Tests/RequestTests.cs

If you need to mock an API designed to the JsonAPI specification you need to work with PATCH requests with a http body. This fix and tests should allow support of PATCH with body and ensure the correct information gets logged.
- Patch requests not configured to support Body
- Add a unit test covering a patch request and logging of results

bug: fix supporting the Patch method and logging the body

---

src/WireMock.Net/Http/HttpClientHelper.cs
test/WireMock.Net.Tests/FluentMockServerTests.Proxy.cs

We need to pass the content headers even if the content is empty.
* fixed issue with passing content headers
* added test for checking the content header when the content is empty

Fix missed content headers

---

src/WireMock.Net/ResponseBuilders/IBodyResponseBuilder.cs
src/WireMock.Net/ResponseBuilders/Response.cs
test/WireMock.Net.Tests/FluentMockServerTests.cs

Adds a small overload for the WithBody method to make callback style mocking even easier.

Feature: add WithBody(req => dostuff) style callback

---

src/WireMock.Net/Owin/AspNetCoreSelfHost.cs

Change listen from loopback to any ip address for dotnetcore2.0 apps

---

examples/WireMock.Net.Console.Proxy.NETCoreApp2/Program.cs
src/WireMock.Net.StandAlone/WireMock.Net.StandAlone.csproj
src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
src/WireMock.Net/Owin/OwinResponseMapper.cs
src/WireMock.Net/Server/FluentMockServer.cs
src/WireMock.Net/WireMock.Net.csproj
test/WireMock.Net.Tests/FluentMockServerTests.Proxy.cs
test/WireMock.Net.Tests/FluentMockServerTests.cs
test/WireMock.Net.Tests/ResponseTests.cs

Related to:
https://github.com/WireMock-Net/WireMock.Net/issues/137
https://github.com/WireMock-Net/WireMock.Net/issues/136
https://github.com/WireMock-Net/WireMock.Net/issues/126

Allow all headers to be set as Response headers

---

src/WireMock.Net/Http/PortUtil.cs
src/WireMock.Net/Owin/WireMockMiddleware.cs
src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
src/WireMock.Net/ResponseMessage.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
src/WireMock.Net/Server/FluentMockServer.cs

- Fix ConcurrentDictionary (#129)
- Change code to get a free port

Fix ConcurrentDictionary (#129)

---

src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
src/WireMock.Net/Server/FluentMockServer.cs

Fix code for .NET Core 2 so that server has cancellation token, and Stop method waits for shutdown.  This resolves issues when using .NET Core 2 and starting/stopping server instances.

Cancellation token not passed to server instance in .NET Core 2

---

src/WireMock.Net/Client/IFluentMockServerAdmin.cs

Resolves https://github.com/WireMock-Net/WireMock.Net/issues/182

Set Content-Type header for PutMappingAsync in the client

---

src/WireMock.Net/Owin/AspNetCoreSelfHost.cs

Should ensure the server is actually listening for client connections. See #196.

Set IsStarted = true in a IApplicationLifetime.ApplicationStarted listener

---

Directory.Build.props
GitHubReleaseNotes.txt
README.md
src/WireMock.Net.StandAlone/SimpleCommandLineParser.cs
test/WireMock.Net.Tests/StandAlone/SimpleCommandLineParserTests.cs

Update SimpleCommandLineParser to handle arguments with key and value

---

examples/WireMock.Net.Service/Program.cs

Fixed issue 223: Example for WireMock as Windows Service throws Exception because of WireMockConsoleLogger

---

WireMock.Net Solution.sln.DotSettings
examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
src/WireMock.Net/Transformers/HandleBarsHelpers.cs
src/WireMock.Net/Transformers/HandleBarsRandom.cs
src/WireMock.Net/WireMock.Net.csproj
test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsRandomTests.cs
test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsRegexTests.cs

Add HandleBars Random functionality (#219)

---

Directory.Build.props
azure-pipelines.yml
src/WireMock.Net/Admin/Mappings/ParamModel.cs
src/WireMock.Net/Matchers/Request/RequestMessageParamMatcher.cs
src/WireMock.Net/RequestBuilders/IParamsRequestBuilder.cs
src/WireMock.Net/RequestBuilders/Request.Params.cs
src/WireMock.Net/RequestBuilders/Request.cs
src/WireMock.Net/RequestMessage.cs
src/WireMock.Net/Serialization/MappingConverter.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
test/WireMock.Net.Tests/RequestMatchers/RequestMessageParamMatcherTests.cs
test/WireMock.Net.Tests/RequestMessageTests.cs

https://github.com/WireMock-Net/WireMock.Net/issues/253

RequestMessageParamMatcher supports Ignore Case for the key

---

Directory.Build.props
examples/WireMock.Net.StandAlone.Net461/App.config
examples/WireMock.Net.StandAlone.Net461/WireMock.Net.StandAlone.Net461.csproj
examples/WireMock.Net.StandAlone.Net461/packages.config
src/WireMock.Net/Matchers/ExactMatcher.cs
src/WireMock.Net/Matchers/MatchScores.cs
src/WireMock.Net/Matchers/Request/RequestMessageParamMatcher.cs
src/WireMock.Net/WireMock.Net.csproj
test/WireMock.Net.Tests/Matchers/ExactMatcherTests.cs
test/WireMock.Net.Tests/RequestBuilders/RequestBuilderUsingMethodTests.cs
test/WireMock.Net.Tests/RequestBuilders/RequestBuilderWithBodyTests.cs
test/WireMock.Net.Tests/RequestBuilders/RequestBuilderWithCookieTests.cs
test/WireMock.Net.Tests/RequestBuilders/RequestBuilderWithHeaderTests.cs
test/WireMock.Net.Tests/RequestBuilders/RequestBuilderWithParamTests.cs
test/WireMock.Net.Tests/RequestBuilders/RequestBuilderWithUrlTests.cs
test/WireMock.Net.Tests/RequestMatchers/RequestMessageParamMatcherTests.cs
test/WireMock.Net.Tests/RequestMessageTests.cs
test/WireMock.Net.Tests/WireMock.Net.Tests.csproj

https://github.com/WireMock-Net/WireMock.Net/issues/255

Fixed Multi Param Match logic

---

src/WireMock.Net/Transformers/ResponseMessageTransformer.cs

Fix ResponseMessageTransformer to not replace BodyAsJson in an original message with transformed results

Fix BodyAsJson transform bug in ResponseMessageTransformer

---

CHANGELOG.md
Directory.Build.props
GitHubReleaseNotes.txt
examples/WireMock.Net.Client/Program.cs
examples/WireMock.Net.Console.Net452.Classic/CustomFileSystemFileHandler.cs
src/WireMock.Net/Client/IFluentMockServerAdmin.cs
src/WireMock.Net/Handlers/IFileSystemHandler.cs
src/WireMock.Net/Handlers/LocalFileSystemHandler.cs
src/WireMock.Net/ResponseMessageBuilder.cs
src/WireMock.Net/Serialization/MappingConverter.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
src/WireMock.Net/Server/FluentMockServer.AdminFiles.cs
test/WireMock.Net.Tests/FLuentMockServerTests.AdminFiles.cs
test/WireMock.Net.Tests/FluentMockServerAdminRestClientTests.cs
test/WireMock.Net.Tests/FluentMockServerTests.Admin.cs
test/WireMock.Net.Tests/FluentMockServerTests.Settings.cs
test/WireMock.Net.Tests/Handlers/LocalFileSystemHandlerTests.cs
test/WireMock.Net.Tests/ResponseBuilders/ResponseWithBodyTests.cs

I've added endpoints for file upload/download/deletion (PUT/GET/DELETE) to allow for testing using files. The code is pretty basic but fulfills my requirements at the moment and has test coverage of happy paths.

[265] Add file upload to allow mocking of file operations

---

src/WireMock.Net/Owin/AspNetCoreSelfHost.cs

This addresses https://github.com/WireMock-Net/WireMock.Net/issues/292 which is known to affect Xamarin Android.
I'm not aware of any other platforms where this is a problem, but if there are any, the principle is the same: if AppContext.BaseDirectory is null, then WebHostBuilder won't work without setting ContentRoot. WireMock.Net wouldn't work at all under that condition before, so the workaround can't hurt - and the workaround is only used in that condition, so platforms where WireMock.Net _did_ work are not affected.
I don't know of any way to unit-test this change, since it's not possible to change AppContext.BaseDirectory dynamically in a test. However, I have tested manually in Xamarin Android and it solved the problem for me.

workaround for AppContext.BaseDirectory being null on some platforms

---

src/WireMock.Net/Util/BodyParser.cs
test/WireMock.Net.Tests/FluentMockServerTests.cs
test/WireMock.Net.Tests/Util/BodyParserTests.cs

This addresses https://github.com/WireMock-Net/WireMock.Net/issues/290 by changing the request-processing behavior from this--
* Is the request method is one of the specific methods that we _know_ can have a body?
* If so, then preserve the request body.
* Otherwise, discard the request body.
--to this:
* Is the request method is one of the specific methods that we _know_ **_cannot_** have a body?
* If so, then discard the request body.
* Otherwise, preserve the request body.
For any of the methods that were already listed in BodyParser.cs, this change has no effect: request bodies will still be discarded for GET or DELETE, preserved for POST or PUT, etc. But for methods that were not specifically mentioned there (like REPORT), the request body (if any) will be preserved. I believe this …

don't strip request body if we don't recognize the request method

---

Directory.Build.props
GitHubReleaseNotes.txt
src/WireMock.Net/ResponseBuilders/Response.cs
test/WireMock.Net.Tests/ResponseBuilders/ResponseWithBodyFromFileTests.cs

Fixed bug 301 by not setting BodyAsFile to null after first use

---

src/WireMock.Net/Util/QueryStringParser.cs
test/WireMock.Net.Tests/Util/QueryStringParserTests.cs

This is a fix for #287; querystring parameters that contain `==` in their value were not being properly parsed, i.e., `?key=value==something`.
The fix here limits splitting each querystring parameter to the first `=` in the string.
I don't see any contributing guidelines, so I'm happy to make changes if need be.  Thank you for a great tool!

Handles case where parameter value contains ==

---

src/WireMock.Net/Server/FluentMockServer.Admin.cs

When both are true - mappings are applied instantly and may affect further requests recording.
It make sense to separate settings and allow to save files without applying them.

Make SaveMapping and SaveMappingToFile settings independent.

---

src/WireMock.Net.StandAlone/StandAloneApp.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
src/WireMock.Net/Settings/IProxyAndRecordSettings.cs
src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
test/WireMock.Net.Tests/FluentMockServerTests.Admin.cs
test/WireMock.Net.Tests/FluentMockServerTests.Proxy.cs

Add blacklist for Request Cookies.

---

src/WireMock.Net/Server/FluentMockServer.LogEntries.cs

We are using wiremock as part of our tests and we found that if we have tests running in parallel we sometimes get an error when calling the `FindLogEntries` method. 
**Error** 
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
```
This is my quick attempt at fixing the above issue. By convert the collection into a new list it shouldn't throw an error if the `LogEntries` collection is updated. 
From a quick google around the `ToList` method itself isn't thread safe either though. So its possible that while the `ToList` method is creating a copy, it fails due to the original collection getting changed.
Thoughts?
@StefH

Fix: Collection was modified exception

---

Directory.Build.props
GitHubReleaseNotes.txt
src/WireMock.Net/Http/HttpClientHelper.cs
src/WireMock.Net/Http/HttpRequestMessageHelper.cs
src/WireMock.Net/Http/HttpResponseMessageHelper.cs
src/WireMock.Net/Http/StringContentHelper.cs
src/WireMock.Net/Util/BodyParser.cs
src/WireMock.Net/WireMock.Net.csproj
test/WireMock.Net.Tests/Http/HttpRequestMessageHelperTests.cs
test/WireMock.Net.Tests/Http/StringContentHelperTests.cs
test/WireMock.Net.Tests/WireMock.Net.Tests.csproj

* remove MimeKitLite and use MediaTypeHeaderValue

Fix ContentType with parameters in Proxy Mode

---

src/WireMock.Net/Matchers/Request/MatchDetail.cs
src/WireMock.Net/Matchers/Request/RequestMatchResult.cs
src/WireMock.Net/Owin/MappingMatcher.cs
src/WireMock.Net/Serialization/LogEntryMapper.cs
test/WireMock.Net.Tests/Matchers/RequestMatchResultTests.cs
test/WireMock.Net.Tests/Owin/MappingMatcherTests.cs

Fix CompareTo in RequestMatchResult

---

src/WireMock.Net/IMapping.cs
src/WireMock.Net/Mapping.cs
src/WireMock.Net/Owin/WireMockMiddleware.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
test/WireMock.Net.Tests/FluentMockServerTests.Proxy.cs

When proxy is enabled the recorded requests are mistaken (IMO) for admin interface requests and skipped in LogEntries. Actually none of requests logged in proxy mode. It is valuable to monitor that while recording.

Fix recorded requests skipped by request logger

---

src/WireMock.Net.StandAlone/StandAloneApp.cs
src/WireMock.Net/Admin/Settings/SettingsModel.cs
src/WireMock.Net/Owin/IWireMockMiddlewareOptions.cs
src/WireMock.Net/Owin/Mappers/IOwinRequestMapper.cs
src/WireMock.Net/Owin/Mappers/OwinRequestMapper.cs
src/WireMock.Net/Owin/MappingMatcher.cs
src/WireMock.Net/Owin/WireMockMiddleware.cs
src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
src/WireMock.Net/Server/FluentMockServer.cs
src/WireMock.Net/Settings/FluentMockServerSettings.cs
src/WireMock.Net/Settings/IFluentMockServerSettings.cs
src/WireMock.Net/Util/BodyParser.cs
test/WireMock.Net.Tests/FluentMockServerTests.Settings.cs
test/WireMock.Net.Tests/Owin/WireMockMiddlewareTests.cs
test/WireMock.Net.Tests/Util/BodyParserTests.cs

AllowBodyForAllHttpMethods

---

src/WireMock.Net/Admin/Mappings/FaultModel.cs
src/WireMock.Net/Admin/Mappings/ResponseModel.cs
src/WireMock.Net/Admin/Requests/LogResponseModel.cs
src/WireMock.Net/Owin/Mappers/OwinResponseMapper.cs
src/WireMock.Net/RequestBuilders/IBodyRequestBuilder.cs
src/WireMock.Net/RequestBuilders/IHeadersAndCookiesRequestBuilder.cs
src/WireMock.Net/RequestBuilders/IParamsRequestBuilder.cs
src/WireMock.Net/ResponseBuilders/FaultType.cs
src/WireMock.Net/ResponseBuilders/IBodyResponseBuilder.cs
src/WireMock.Net/ResponseBuilders/IFaultRequestBuilder.cs
src/WireMock.Net/ResponseBuilders/Response.WithFault.cs
src/WireMock.Net/ResponseBuilders/Response.cs
src/WireMock.Net/ResponseMessage.cs
src/WireMock.Net/Serialization/LogEntryMapper.cs
src/WireMock.Net/Serialization/MappingConverter.cs
src/WireMock.Net/Server/FluentMockServer.Admin.cs
src/WireMock.Net/Transformers/ResponseMessageTransformer.cs
src/WireMock.Net/WireMock.Net.csproj
test/WireMock.Net.Tests/Owin/Mappers/OwinResponseMapperTests.cs
test/WireMock.Net.Tests/ResponseBuilders/ResponseWithWithFaultTests.cs
test/WireMock.Net.Tests/Serialization/LogEntryMapperTests.cs
test/WireMock.Net.Tests/WireMock.Net.Tests.csproj

Add support for Faults

---

src/WireMock.Net/Server/IRespondWithAProvider.cs
src/WireMock.Net/Server/RespondWithAProvider.cs
test/WireMock.Net.Tests/StatefulBehaviorTests.cs
test/WireMock.Net.Tests/WireMock.Net.Tests.csproj

- Add support for submitting int values for states and scenarios
- 1 and "1" are the same state/scenario
- Add unit tests

Support int values for states and scenario naming

---

src/WireMock.Net/Server/WireMockServer.Admin.cs

Using HTTP `Delete `verb, a user can send multiple mapping jsons (with GUIDs) for deletion.
Note: `AllowBodyForAllHttpMethods `must be set to true.

Admin Delete with mappings in body

---

src/WireMock.Net/Http/HttpClientHelper.cs
src/WireMock.Net/Http/HttpResponseMessageHelper.cs
src/WireMock.Net/Owin/IWireMockMiddlewareOptions.cs
src/WireMock.Net/Owin/Mappers/OwinRequestMapper.cs
src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
src/WireMock.Net/ResponseBuilders/Response.cs
src/WireMock.Net/Server/WireMockServer.Admin.cs
src/WireMock.Net/Server/WireMockServer.cs
src/WireMock.Net/Settings/IWireMockServerSettings.cs
src/WireMock.Net/Settings/WireMockServerSettings.cs
src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
src/WireMock.Net/Util/BodyParser.cs
test/WireMock.Net.Tests/RequestMatchers/RequestMessageBodyMatcherTests.cs
test/WireMock.Net.Tests/Util/BodyParserTests.cs

I had problems mocking a system with very specific requirements concerning JSON formatting. To make this work, I implemented an option to disable JSON reformatting.

Option to disable JSON deserialization

---

azure-pipelines-ci-linux.yml
azure-pipelines-ci.yml
src/WireMock.Net/Owin/WireMockMiddleware.cs
src/WireMock.Net/Serialization/LogEntryMapper.cs
test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
test/WireMock.Net.Tests/WireMockServer.Proxy.cs

https://github.com/WireMock-Net/WireMock.Net/issues/467

Fix unhandled exception when target is unavailable

---

test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsTests.cs
test/WireMock.Net.Tests/WireMock.Net.Tests.csproj

Porting over the tests from the original project.

Bring in the WireMock.Net.FluentAssertions tests

---

src/WireMock.Net.StandAlone/StandAloneApp.cs
src/WireMock.Net/Server/FluentMockServer.cs
src/WireMock.Net/Server/WireMockServer.Admin.cs
src/WireMock.Net/Settings/FluentMockServerSettings.cs
src/WireMock.Net/Settings/IFluentMockServerSettings.cs
src/WireMock.Net/Settings/IProxyAndRecordSettings.cs
src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
test/WireMock.Net.Tests/ResponseBuilders/ResponseWithStatusCodeTests.cs
test/WireMock.Net.Tests/WireMockServer.Proxy.cs

https://github.com/WireMock-Net/WireMock.Net/issues/489

Mark FluentMockServer, FluentMockServerSettings, BlacklistedHeaders and BlacklistedCookies as obsolete

---

src/WireMock.Net.StandAlone/WireMock.Net.StandAlone.csproj
src/WireMock.Net/Http/HttpClientHelper.cs
src/WireMock.Net/Matchers/CSharpCodeMatcher.cs
src/WireMock.Net/WireMock.Net.csproj

Attempting to remove a dependency on `Microsoft.AspNetCore` packages for projects targetting netcoreapp3.0 or greater
#507

Adding netcoreapp3.1 as a target framework

---

examples/WireMock.Net.WebApplication.NETCore2/web.config
examples/WireMock.Net.WebApplication.NETCore3/App.cs
examples/WireMock.Net.WebApplication.NETCore3/IWireMockService.cs
examples/WireMock.Net.WebApplication.NETCore3/Program.cs
examples/WireMock.Net.WebApplication.NETCore3/Properties/launchSettings.json
examples/WireMock.Net.WebApplication.NETCore3/WireMock.Net.WebApplication.NETCore3.csproj
examples/WireMock.Net.WebApplication.NETCore3/WireMockService.cs
examples/WireMock.Net.WebApplication.NETCore3/web.config

* Apply `ILogger`, `IOptions`, `IHostedService` patterns to .NET Core 3.1 example
* Trim unnecessary bits
* Enforce 'Out-of-process' hosting model or the example will not run correctly
* Consolidated line-ending in two files

Update .NET Core 3.1 example

---

src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard.cs
src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard13.cs
src/WireMock.Net/Owin/AspNetCoreSelfHost.cs

* Allow Kestrel limits options to be overridden with values of config files and environment variables (see [related Microsoft documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#kestrel-options)).

Make kestrel limits configurable

---

src/WireMock.Net/Owin/Mappers/OwinResponseMapper.cs

I noticed two things while updating from 1.4.1 to 1.4.4.
First - is an issue with formatting in Date header.
The DateTimeFormat.RFC1123Pattern can't be used with string.Format, since it doesn't seem to have {0} placeholder. Also the RFC1123Pattern is supplied not only as the 'format' parameter, but also as 'arg0' parameter.
I replaced string.Format with date.ToString(...).
Here is the output from simple console example:
```
Current: ddd, dd MMM yyyy HH':'mm':'ss 'GMT'
Fix: Thu, 11 Feb 2021 11:53:02 GMT
```
The second thing - it looks like the date header can't be in local time (at least developer.mozilla.org says that. I didn't read the actual standard, so might be wrong).
I'm not sure if there is a reason current implementation uses DateTime.Now instead of DateTime.UtcNow, but I also …

Fix response date header

---

src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard.cs
src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
test/WireMock.Net.Tests/WireMockServerTests.cs

Fixes #554 
Remove an approximate two second delay in response to the first request from a new socket connection, apparently only occuring on some Windows 10 machines when using .Net Core.
A side-effect of this fix is that is also allows connections to IPv6 addresses.

Remove 2 second delay from first response and add IPv6 address support

---

src/WireMock.Net/Matchers/Request/RequestMessageBodyMatcher.cs
test/WireMock.Net.Tests/RequestMatchers/RequestMessageBodyMatcherTests.cs
test/WireMock.Net.Tests/RequestWithBodyTests.cs

Fix match logic for exact bytearray

---

WireMock.Net Solution.sln.DotSettings
examples/WireMock.Net.OpenApiParser.ConsoleApp/Run.cs
src/WireMock.Net.OpenApiParser/Extensions/WireMockServerExtensions.cs
src/WireMock.Net.OpenApiParser/IWireMockOpenApiParser.cs
src/WireMock.Net.OpenApiParser/Mappers/OpenApiPathsMapper.cs
src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserExampleValues.cs
src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserSettings.cs
src/WireMock.Net.OpenApiParser/Types/ExampleValueType.cs
src/WireMock.Net.OpenApiParser/Utils/ExampleValueGenerator.cs
src/WireMock.Net.OpenApiParser/WireMock.Net.OpenApiParser.csproj
src/WireMock.Net.OpenApiParser/WireMockOpenApiParser.cs

Add possibility to use settings to generate MappingModel models with wildcard path parameters.
#608

Add possibility to use settings to generate MappingModel models with wildcard path parameters.

---

examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
src/WireMock.Net/Owin/IWireMockMiddlewareOptions.cs
src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
src/WireMock.Net/Server/WireMockServer.cs
src/WireMock.Net/Settings/IWireMockServerSettings.cs
src/WireMock.Net/Settings/WireMockServerSettings.cs

Since we allow to add custom middleware to WireMock's ASP.NET Core pipeline (using PreWireMockMiddlewareInit/PostWireMockMiddlewareInit), it would make sense to also allow to add custom service registration to ASP.NET Core DI. My specific use case is adding Azure Application Insights telemetry to WireMock's ASP.NET Core host to track external calls from WireMock (mappings with proxy).

Allow to add custom service registrations when using ASP.NET Core

---

src/WireMock.Net.OpenApiParser/Settings/IWireMockOpenApiParserExampleValues.cs
src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserDynamicExampleValues.cs
src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserExampleValues.cs
src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserSettings.cs
src/WireMock.Net.OpenApiParser/Utils/ExampleValueGenerator.cs
src/WireMock.Net.OpenApiParser/WireMock.Net.OpenApiParser.csproj

Hello @StefH,
I hope you're doing well,
I added the support to Data Generation via `WireMockOpenApiParserSettings` the idea is when the property `DynamicExamples` is true Wiremock.net will be able to randomize the data. I used your awesome library [RandomDataGenerator](https://github.com/StefH/RandomDataGenerator), thanks a lot. 
I hope to see this change soon in nuget, thank you very much Stef, Wiremock.Net has been very useful to me.

Support examples random data generation

---

src/WireMock.Net.OpenApiParser/Mappers/OpenApiPathsMapper.cs
src/WireMock.Net.OpenApiParser/WireMockOpenApiParser.cs

Hello @StefH ,
This change support the basepath definition in v2 and servers in  v3. The idea is when the file has a relative or absolute path this is attached at the path.
Thanks.

Support basepath from servers

---

src/WireMock.Net.OpenApiParser/Utils/ExampleValueGenerator.cs

Hello @StefH ,
This PR contains the capability to support examples when it is defined in the properties:
```
"schemas": {
"Order": {
"type": "object",
"properties": {
"id": {
"type": "integer",
"format": "int64",
"example": 10
},
"petId": {
"type": "integer",
"format": "int64",
"example": 198772
},
"quantity": {
"type": "integer",
"format": "int32",
"example": 7
},
"shipDate": {
"type": "string",
"format": "date-time"
},
"status": {
"type": "string",
"description": "Order Status",
"example": "approved",
"enum": [
"placed",
"approved",
"delivered"
]
},
"complete": {
"type": "boolean"
}
},
"xml": {
"name": "order"
}
},
}
```
The response looks like this:
```
"Response": {
"StatusCode": 200,
"BodyAsJson": {
"id": 10,
"petId": 198772,
"quantity": 7,
"shipDate": …
```

Support examples in properties

---

src/WireMock.Net.OpenApiParser/Mappers/OpenApiPathsMapper.cs

Hello @StefH,
I'm trying to add the support to request body, I'm following the same logic used in the response, I'm facing a problem when I try to use `BodyAsJson` in the `RequestModel` 'cause it does not exist, I'm using `Body` but it does not work as I expected, could you have idea why it is happening? 
I appreciate your help.

Support RequestBody

---

src/WireMock.Net.OpenApiParser/Mappers/OpenApiPathsMapper.cs
src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserSettings.cs

Hello @StefH  @JanuszRybinski,
This is the PR related with this #692, the idea is allow not case sensitive in Headers, Query Params, Request Body and examples.
Regards.

Allow configure IgnoreCase in settings

---

examples/WireMock.Net.OpenApiParser.ConsoleApp/DynamicDataGeneration.cs
examples/WireMock.Net.OpenApiParser.ConsoleApp/OpenApiFiles/Swagger_Customer_V2.0.json
examples/WireMock.Net.OpenApiParser.ConsoleApp/Program.cs
examples/WireMock.Net.OpenApiParser.ConsoleApp/Run.cs
examples/WireMock.Net.OpenApiParser.ConsoleApp/WireMock.Net.OpenApiParser.ConsoleApp.csproj
src/WireMock.Net.OpenApiParser/Settings/IWireMockOpenApiParserExampleValues.cs
src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserDynamicExampleValues.cs
src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserExampleValues.cs
src/WireMock.Net.OpenApiParser/Utils/ExampleValueGenerator.cs

@StefH  Having ope api Schema we can use settings like max-length in case of a string to generate more accurate mock data when you implement your dynamic examples

Provide open api schema to dynamic examples generator so you can generate accurate data

---

src/WireMock.Net.Abstractions/WireMock.Net.Abstractions.csproj
src/WireMock.Net/Transformers/Transformer.cs
test/WireMock.Net.Tests/ResponseBuilders/ResponseWithTransformerTests.cs

Fixed 'Response BodyAsJson with JArray does not work'

---

src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.cs
test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsTests.cs

Hi, i've added some assertions for request methods.

Add assertions for request methods

---

examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
src/WireMock.Net/Owin/WireMockMiddleware.cs

little cleaner skipping the await, fix example

Tweak middleware and fix bug in example

---

src/WireMock.Net/Http/WebhookSender.cs
test/WireMock.Net.Tests/WireMockServer.WebhookTests.cs

Tried to use this new feature at work, but it called the Webhook URL with the non-transformed URL. I've fixed the code and also fixed the test which was a false positive.

Webhook Templating: Use the transformed URL to create the HttpRequestMessage

---

Directory.Build.props
azure-pipelines-ci.yml
examples/WireMock.Net.Service/App.config
examples/WireMock.Net.Service/WireMock.Net.Service.csproj
examples/WireMock.Net.Service/packages.config
test/WireMock.Net.Tests/WireMock.Net.Tests.csproj

https://github.com/coverlet-coverage/coverlet/issues/1391

Fix Linux CI build + Fix opencover

---

src/WireMock.Net/Server/WireMockServer.ConvertMapping.cs

Hi,
this mapping was missing, so when using the Admin API the UseWebhooksFireAndForget flag was always false.

Add UseWebhooksFireAndForget to Server ConvertMapping

---

src/WireMock.Net/Settings/WireMockServerSettings.cs

Fix Self referencing loop detected for property 'Parent'
`Newtonsoft.Json.JsonSerializationException : Self referencing loop detected for property 'Parent' with type 'System.Globalization.CultureInfo'. Path 'Culture'.
StackTrace:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(Jso …

Fix Self referencing loop detected for property

---

src/WireMock.Net/Serialization/MappingConverter.cs
test/WireMock.Net.Tests/Serialization/MappingConverterTests.ToCSharpCode_With_Builder_And_AddStartIsFalse.verified.txt
test/WireMock.Net.Tests/Serialization/MappingConverterTests.ToCSharpCode_With_Builder_And_AddStartIsTrue.verified.txt
test/WireMock.Net.Tests/Serialization/MappingConverterTests.ToCSharpCode_With_Server_And_AddStartIsFalse.verified.txt
test/WireMock.Net.Tests/Serialization/MappingConverterTests.ToCSharpCode_With_Server_And_AddStartIsTrue.verified.txt
test/WireMock.Net.Tests/WireMockAdminApiTests.IWireMockAdminApi_GetMappingsCode.verified.txt

This PR removes redundant ")" character from header names.

Fix C# mapping code generator for header names

---

src/WireMock.Net/Serialization/MappingConverter.cs
test/WireMock.Net.Tests/WireMockAdminApiTests.IWireMockAdminApi_GetMappingsCode.verified.txt
test/WireMock.Net.Tests/WireMockAdminApiTests.cs

This PR brings the following improvements:
- Add quote escaping in generated C# strings
- Handle JSON in the response body. Json is converted to C# anonymous object definition and fed into `WithBodyAsJson` method.

C# code generator improvements

---

src/WireMock.Net/Matchers/AbstractJsonPartialMatcher.cs
test/WireMock.Net.Tests/Matchers/JsonPartialMatcherTests.cs

Closes #971 
Adds an ability for a JsonPartialMatcher to match Guid and String values when the matcher is configured using an anonymous object with Guid fields

JsonPartialMatcher - match guid and string

---

src/WireMock.Net/Matchers/JSONPathMatcher.cs
test/WireMock.Net.Tests/Matchers/JsonPathMatcherTests.cs

The .SelectToken method accept string path selection and JSONPath queries. The current code works only for the queries because the result is JObject. When the string path is selected the result is JValue and event with a valid result the code the code doesn't return valued result.
https://www.newtonsoft.com/json/help/html/SelectToken.htm

Update JSONPathMatcher.cs to cover the string path selection to a child

---

src/WireMock.Net.Abstractions/Admin/Mappings/MatcherModel.cs
src/WireMock.Net.Abstractions/Admin/Mappings/XmlNamespace.cs
src/WireMock.Net/Matchers/XPathMatcher.cs
src/WireMock.Net/Serialization/MatcherMapper.cs
test/WireMock.Net.Tests/Matchers/XPathMatcherTests.cs
test/WireMock.Net.Tests/Serialization/MatcherMapperTests.cs

We have round about 4800 WCF Services in our landscape, thus this faker is really helpful. In order to write more easy request body matchers I would like to write more easy xpath expressions using the xpath matcher as follows:
``` json
{
"Title": "wcf test",
"Request": {
"Path": {
"Matchers": [
{
"Name": "WildcardMatcher",
"Pattern": "/MyService.svc"
}
]
},
"Methods": [
"post"
],
"Headers": [
{
"Name": "Content-Type",
"Matchers": [
{
"Name": "WildcardMatcher",
"Pattern": "text/xml; charset=utf-8",
"IgnoreCase": true
}
],
"IgnoreCase": true
},
{
"Name": "SOAPAction",
"Matchers": [
{
"Name": "WildcardMatcher",
"Pattern": "*urn://MyService/Query*",
"IgnoreCase": true
}
],
"IgnoreCase": true
}
],
"Body": {
"Matcher": {
"Name": "XPathMatcher",
"Pattern": "/s:Envelope/s:Body/q:QueryRequest", …
```

Support for xml namespaces in XPathMatcher

---

src/WireMock.Net.RestClient/IWireMockAdminApi.cs
src/WireMock.Net/Server/WireMockServer.Admin.cs
test/WireMock.Net.Tests/WireMockAdminApiTests.cs

- Renamed `FindRequestByMappingGuidAsync ` to `FindRequestsByMappingGuidAsync ` and changed its return type to `IList<LogEntryModel>`
- Changed the admin server implementation to return a list
Relates to #1039

Change FindRequestByMappingGuidAsync to return a collection of entries

---

src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.AtUrl.cs
src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.FromClientIP.cs
src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.UsingMethod.cs
src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.WithBody.cs
src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.WithHeader.cs
src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.WithProxy.cs
src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.cs
test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsExtensions.cs
test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsTests.cs

Make WireMockAssertions extendable

---

src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.WithBody.cs
src/WireMock.Net/Extensions/AnyOfExtensions.cs
test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsTests.cs

Fix FluentAssertions (actual body is not displayed in error message)

---

src/WireMock.Net/Logging/WireMockConsoleLogger.cs

In Linqpad, the "console" is [just a facade](https://forum.linqpad.net/discussion/451/some-of-console-properties-are-not-working) over web browser output, so calling `Console.OutputEncoding = System.Text.Encoding.UTF8` in the constructor for `WireMockConsoleLogger` throws an exception.
This PR adds a `try..catch` block to that code, so that the logger can be used in Linqpad (and any other non-standard consoles).

Use try..catch to set encoding in WireMockConsoleLogger

---

src/WireMock.Net.Testcontainers/WireMock.Net.Testcontainers.csproj
src/WireMock.Net.Testcontainers/WireMockContainer.cs
src/WireMock.Net.Testcontainers/WireMockContainerBuilder.cs

Made changes to accommodate breaking change in testcontainers-dotnet 3.9
[3.9.0](https://github.com/testcontainers/testcontainers-dotnet/releases/tag/3.9.0)
[1146](https://github.com/testcontainers/testcontainers-dotnet/pull/1146)
[1100](https://github.com/testcontainers/testcontainers-dotnet/pull/1100)

Made changes to accommodate breaking change in testcontainers-dotnet 3.9

---

src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard.cs
test/WireMock.Net.Tests/Facts/IgnoreOnContinuousIntegrationFact.cs
test/WireMock.Net.Tests/WireMockServerTests.cs

To listen on all available IPs this fix allows to use the following URL:
```
var settings = new WireMockServerSettings
{
Urls = new string[] { "http://0.0.0.0:80" },
};
var server = WireMockServer.Start(settings);
```
I tried to add a test, but I think the test can be improved.
Could be split in a test for IPv4 and IPv6 and maybe the naming is not perfect.
Getting all IPs could be moved into a utility method ...
Feel free to improve afterwards.

Fix listen on AnyIP for url 0.0.0.0

---

src/WireMock.Net/Owin/WireMockMiddleware.cs

Hi there, 
Coming back to this issue: #1086
I wound a way to regain the functionality by creating a custom logger and then throw exceptions once it matches. So:
```csharp
WireMockServer.Start(
new WireMockServerSettings()
{
Logger = new WiremockLogger(_log),
HostingScheme = HostingScheme.HttpAndHttps,
}
);
```
```csharp
public class WiremockLogger : IWireMockLogger
{
private readonly ILog _log;
public WiremockLogger(ILog log)
{
_log = log;
}
public void Debug(string formatString, params object[] args)
{
_log.Debug(formatString, args);
}
public void Info(string formatString, params object[] args)
{
_log.Information(formatString, args);
}
public void Warn(string formatString, params object[] args)
{
_log.Warning(formatString, args);
if (formatString.Contains("No matching mapping found")) …
```

pass in the request when no matching is found to the warn logger

---

src/WireMock.Net/Server/WireMockServer.LogEntries.cs

Fix ArgumentException in FindLogEntries

---

src/WireMock.Net.Abstractions/Server/IWireMockServer.cs
src/WireMock.Net.RestClient/IWireMockAdminApi.cs
src/WireMock.Net/Matchers/Helpers/BodyDataMatchScoreCalculator.cs
src/WireMock.Net/Matchers/ProtoBufMatcher.cs
src/WireMock.Net/RequestBuilders/IBodyRequestBuilder.cs
src/WireMock.Net/RequestBuilders/Request.cs
src/WireMock.Net/ResponseBuilders/Response.WithHeaders.cs
src/WireMock.Net/ResponseBuilders/Response.cs
src/WireMock.Net/Serialization/MappingConverter.cs
src/WireMock.Net/Serialization/MatcherMapper.cs
src/WireMock.Net/Server/IRespondWithAProvider.cs
src/WireMock.Net/Server/RespondWithAProvider.cs
src/WireMock.Net/Server/WireMockServer.ConvertMapping.cs
src/WireMock.Net/Util/PortUtils.cs
src/WireMock.Net/Util/ProtoDefinitionHelper.cs
test/WireMock.Net.Tests/AdminApi/WireMockAdminApiTests.GetMappings.cs
test/WireMock.Net.Tests/AdminApi/WireMockAdminApiTests.HttpClient_GetMappingsAsync_WithBodyAsProtoBuf_ShouldReturnCorrectMappingModels.verified.txt
test/WireMock.Net.Tests/AdminApi/WireMockAdminApiTests.PostMappings.cs
test/WireMock.Net.Tests/AdminApi/WireMockAdminApiTests.cs
test/WireMock.Net.Tests/Grpc/WireMockServerTests.Grpc.cs
test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
test/WireMock.Net.Tests/WireMockServer.Admin.cs
test/WireMock.Net.Tests/__admin/mappings/protobuf-mapping-1.json
test/WireMock.Net.Tests/__admin/mappings/protobuf-mapping-2.json
test/WireMock.Net.Tests/__admin/mappings/protobuf-mapping-3.json
test/WireMock.Net.Tests/__admin/mappings/protobuf-mapping-4.json

Fix ProtoBuf mapping.json

---

examples/WireMock.Net.WebApplication.NET6/WireMockService.cs
src/WireMock.Net.TUnit/TUnitWireMockLogger.cs
src/WireMock.Net.xUnit/TestOutputHelperWireMockLogger.cs
src/WireMock.Net/Owin/WireMockMiddleware.cs

I spent way too much time in the debugger trying to figure out why the mapping was not found. 
It was found, but an exception occurred during the mapping, leading to a misleading message.
As an aside, the exception occurred because I called `.WithMapping()` before I called `.AddProtoDefinition()`...

Add exception message to logging when mapping fails due to an exception.

---

src/WireMock.Net.AspNetCore.Middleware/HttpDelegatingHandler/WireMockDelegationHandler.cs
test/WireMock.Net.Middleware.Tests/IntegrationTests.cs
test/WireMock.Net.TestWebApplication/Program.cs
test/WireMock.Net.TestWebApplication/TaskQueue.cs
test/WireMock.Net.TestWebApplication/TestBackgroundService.cs

While attempting to use Wiremock Middle in an application that uses hosted services i noticed that it breaks and throws an `ArgumentNullException` .
See #1284 
The problem is that `IHttpContextAccessor.HttpContext` can not be relied upon to always be available.
It would be best if `WireMockDelegationHandler` can fallback gracefully if `HttpContext` is null, which is expected in some cases.
I changed `IsWireMockRedirectHeaderSetToTrue` and `TryGetDelayHeaderValue` in `WireMockDelegationHandler` to default to false if `HttpContext` is null.
I created a test to check that it works when started in a hosted service.
The `X-WireMock-Redirect` and `X-WireMock-Response-Delay` headers are obviously not going to work as expected when mocking a request from a background service, maybe this needs to …

Enable support for WireMock Middleware in Hosted Services

---

azure-pipelines-ci.yml
examples-Aspire/AspireApp1.AppHost/AspireApp1.AppHost.csproj
examples-Aspire/AspireApp1.AppHostOriginal/AspireApp1.AppHostOriginal.csproj
src/WireMock.Net.Aspire/WireMock.Net.Aspire.csproj
src/WireMock.Net.Aspire/WireMockInspector.cs
src/WireMock.Net.Aspire/WireMockServerBuilderExtensions.cs
test/WireMock.Net.Aspire.TestAppHost/WireMock.Net.Aspire.TestAppHost.csproj
test/WireMock.Net.Aspire.Tests/WireMock.Net.Aspire.Tests.csproj
test/WireMock.Net.Aspire.Tests/WireMockServerBuilderExtensionsTests.cs

This will add a new command to the Aspire Dashboard on a WireMock resource to launch the WireMockInspector tool.
Also upgrades Aspire to 9.2.0.
Signed-off-by: Jonathan Mezach <jonathan.mezach@rr-wfm.com>

Add an launch inspector command to Aspire Dashboard

---

src/WireMock.Net/Http/ByteArrayContentHelper.cs
src/WireMock.Net/Http/HttpRequestMessageHelper.cs
src/WireMock.Net/Http/StringContentHelper.cs
test/WireMock.Net.Tests/Http/HttpRequestMessageHelperTests.cs

Content-Type multipart/form-data header should also be proxied

---

src/WireMock.Net/Util/CSharpFormatter.cs

When trying to convert static mapping to C# code, I ran into an exception when the body is a top-level array rather than a pure string or a (non-array) JSON object.
The problem is that this code doesn't distinguish between arrays and objects, and assumes that every non-null that isn't a string is an object:
```cs
case BodyType.Json:
if (bodyData.BodyAsJson is string bodyStringValue)
{
sb.AppendLine($"        .WithBody({ToCSharpStringLiteral(bodyStringValue)})");
}
else if (bodyData.BodyAsJson is { } jsonBody)
{
var anonymousObjectDefinition = ConvertToAnonymousObjectDefinition(jsonBody);
sb.AppendLine($"        .WithBodyAsJson({anonymousObjectDefinition})");
}
break;
```
My solution is to load a JToken instead of a JObject in ConvertToAnonymousObjectDefinition, which seems like the …

Fix errors when converting response bodies with top-level JSON arrays to C# code

---

src/WireMock.Net.Testcontainers/WireMock.Net.Testcontainers.csproj
test/WireMock.Net.Tests/Testcontainers/TestcontainersTests.cs
test/WireMock.Net.Tests/WireMock.Net.Tests.csproj

The Testcontainers dependency Docker.DotNet was bumped to 3.128.1 and is not binary compatible with previous version. When a user has a direct dependency on Testcontainers 4.5.0, WireMock.Net.Testcontainers fails with :
```plain
System.MissingMethodException : Method not found: 'Docker.DotNet.DockerClient Docker.DotNet.DockerClientConfiguration.CreateClient(System.Version)'
```
- #1310

Bump Testcontainers version to 4.5.0

---

examples/WireMock.Net.TestcontainersExample/Program.cs
test/WireMock.Net.Tests/Testcontainers/TestcontainersTests.Grpc.cs
test/WireMock.Net.Tests/Testcontainers/TestcontainersTests.cs

Remove unecessary call to `AutoRemove()`, `CleanUp()` to not mislead users of WireMock.Net.
- TODO

Use default resource cleaning behavior in test

---

src/WireMock.Net.Shared/Matchers/Helpers/BodyDataMatchScoreCalculator.cs
test/WireMock.Net.Tests/RequestMatchers/RequestMessageBodyMatcherTests.cs

Fixes an issue where body payloads would fail to be matched if the matcher was created using a `byte[]` value and the bytes represented valid JSON.
- #1338

Fixes an issue with matching JSON bodies as bytes
