- examples/WireMock.Net.Console.Record.NETCoreApp/Program.cs
- examples/WireMock.Net.ConsoleApplication/MainApp.cs
Just changing the files back that I shouldn't have made in the first place. I wasn't expecting the PR to be merged so quickly :-)
> Revert changes that were made by mistake in prior PR

- src/WireMock.Net/Client/IFluentMockServerAdmin.cs
- test/WireMock.Net.Tests/ClientTests.cs
> Fixed issue #76

- Directory.Build.props
- README.md
- src/WireMock.Net/ResponseBuilders/Response.cs
- src/WireMock.Net/Server/FluentMockServer.Admin.cs
- src/WireMock.Net/Transformers/ResponseMessageTransformer.cs
- test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsTests.cs
> Support Dynamic response files using Handlebars templating

- test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsTests.cs
> Add unit test for JsonPath and BodyAsFile mapping

- Directory.Build.props
- GitHubReleaseNotes.txt
- WireMock.Net Solution.sln
- src/WireMock.Net/IMapping.cs
- src/WireMock.Net/Mapping.cs
- src/WireMock.Net/Owin/WireMockMiddleware.cs
- src/WireMock.Net/Server/FluentMockServer.Admin.cs
- src/WireMock.Net/Server/FluentMockServer.LogEntries.cs
- src/WireMock.Net/Util/CloneUtils.cs
- src/WireMock.Net/WireMock.Net.csproj
https://github.com/WireMock-Net/WireMock.Net/issues/308
> Fix LogEntries: collection was modified exception

- src/WireMock.Net/WireMock.Net.csproj
https://github.com/WireMock-Net/WireMock.Net/issues/377
> Set handlebars dependency for .net 4.5.1 to fixed value

- src/WireMock.Net/ResponseBuilders/Response.cs
- src/WireMock.Net/Server/FluentMockServer.Admin.cs
- src/WireMock.Net/Util/BodyParser.cs
- src/WireMock.Net/Util/JsonUtils.cs
> Correctly support DateTime pattern as string in ExactMatcher

- src/WireMock.Net.StandAlone/StandAloneApp.cs
> Fix for invalid cast exception

- src/WireMock.Net/Matchers/RegexMatcher.cs
simple fix - just allow multi line regex matching.
> Support multi line wild card matching

- src/WireMock.Net.Abstractions/WireMock.Net.Abstractions.csproj
- src/WireMock.Net.RestClient/WireMock.Net.RestClient.csproj
- src/WireMock.Net.StandAlone/WireMock.Net.StandAlone.csproj
- src/WireMock.Net/WireMock.Net.csproj
> GH161: Fix SourceLink support

- azure-pipelines-ci.yml
https://github.com/SonarSource/sonar-scanner-msbuild/issues/915
> Fix dotnet-sonarscanner

- examples/WireMock.Net.StandAlone.NETCoreApp/Program.cs
- src/WireMock.Net/Matchers/Request/RequestMessageBodyMatcher.cs
- src/WireMock.Net/RequestBuilders/IBodyRequestBuilder.cs
- src/WireMock.Net/RequestBuilders/Request.WithBody.cs
- test/WireMock.Net.Tests/RequestWithBodyTests.cs
https://github.com/WireMock-Net/WireMock.Net/issues/593
> Add possibility to the WithBody() to use IBodyData

- src/WireMock.Net.OpenApiParser/Utils/ExampleValueGenerator.cs
- test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsHumanizerTests.cs
Hello @StefH ,
The idea here is support that when a property will have an enum one of them is selected random.
> Support enums in properties

- src/WireMock.Net.OpenApiParser/WireMock.Net.OpenApiParser.csproj
@StefH 
RamlToOpenAPIConverter has been updated to 0.5.0
Would you please include this capability in new release (:
> RamlToOpenAPI updated to 0.5.0

- src/WireMock.Net.OpenApiParser/Mappers/OpenApiPathsMapper.cs
Hello @StefH @JanuszRybinski,
This is the PR related with this #692, the idea is filter required property in Headers, Query Params, Request Body.
Regards.
> Filter required property in headers, query params, request body

- azure-pipelines-ci.yml
- azure-pipelines-nuget.yml
https://github.com/NuGet/Home/issues/11601
> Fixed bug "dotnet nuget push -n"

- src/WireMock.Net/Matchers/Request/RequestMessageHeaderMatcher.cs
- test/WireMock.Net.Tests/RequestMatchers/RequestMessageHeaderMatcherTests.cs
- test/WireMock.Net.Tests/RequestTests.cs
> Fix WithHeader when using RejectOnMatch

- test/WireMock.Net.Tests/ResponseBuilders/ResponseWithTransformerTests.cs
> Add unit test example for Transformer Handlebars String.Append String.Join

- examples/WireMock.Net.Console.NET6/WireMock.Net.Console.NET6.csproj
- src/WireMock.Net.Abstractions/Admin/Mappings/MappingModel.cs
- src/WireMock.Net.Abstractions/Admin/Mappings/ResponseModel.cs
- src/WireMock.Net.Abstractions/IResponseMessage.cs
- src/WireMock.Net/IMapping.cs
- src/WireMock.Net/Json/DynamicJsonClassOptions.cs
- src/WireMock.Net/Json/DynamicPropertyWithValue.cs
- src/WireMock.Net/Json/FloatBehavior.cs
- src/WireMock.Net/Json/IntegerBehavior.cs
- src/WireMock.Net/Json/JObjectExtensions.cs
- src/WireMock.Net/Mapping.cs
- src/WireMock.Net/Matchers/LinqMatcher.cs
- src/WireMock.Net/ResponseBuilders/IResponseBuilder.cs
- src/WireMock.Net/ResponseBuilders/Response.cs
- src/WireMock.Net/ResponseMessage.cs
- src/WireMock.Net/Serialization/MappingConverter.cs
- src/WireMock.Net/Serialization/ProxyMappingConverter.cs
- src/WireMock.Net/Server/IRespondWithAProvider.cs
- src/WireMock.Net/Server/RespondWithAProvider.cs
- src/WireMock.Net/Server/WireMockServer.ConvertMapping.cs
- src/WireMock.Net/Transformers/TransformModel.cs
- src/WireMock.Net/Transformers/Transformer.cs
- src/WireMock.Net/Util/JsonUtils.cs
- src/WireMock.Net/WireMock.Net.csproj
- test/WireMock.Net.Tests/Owin/WireMockMiddlewareTests.cs
- test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsLinqTests.cs
- test/WireMock.Net.Tests/ResponseBuilders/ResponseWithTransformerTests.cs
- test/WireMock.Net.Tests/Serialization/MappingConverterTests.ToCSharpCode.cs
- test/WireMock.Net.Tests/Serialization/MappingConverterTests.cs
- test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
> Add 'Data' to response which can be used during transforming the response

- src/WireMock.Net.Abstractions/Admin/Mappings/CookieModel.cs
- src/WireMock.Net.Abstractions/Admin/Mappings/HeaderModel.cs
> Update comments for models

- src/WireMock.Net.FluentAssertions/WireMock.Net.FluentAssertions.csproj
https://github.com/WireMock-Net/WireMock.Net/issues/928
> Add ".NET Framework 4.7" to WireMock.Net.FluentAssertions

- src/WireMock.Net/Matchers/Request/RequestMessageMultiPartMatcher.cs
- test/WireMock.Net.Tests/Client/Builders/AdminApiMappingBuilderTests.GetMappingBuilder_BuildAndPostAsync.verified.txt
- test/WireMock.Net.Tests/Client/Builders/AdminApiMappingBuilderTests.cs
- test/WireMock.Net.Tests/RequestMatchers/RequestMessageMultiPartMatcher.cs
Fixes the issue discussed here:
https://github.com/WireMock-Net/WireMock.Net/issues/1119
> Multipart Matcher Fix

- WireMock.Net Solution.sln
- src/WireMock.Net.AwesomeAssertions/Assertions/WireMockANumberOfCallsAssertions.cs
- src/WireMock.Net.AwesomeAssertions/Assertions/WireMockAssertions.AtUrl.cs
- src/WireMock.Net.AwesomeAssertions/Assertions/WireMockAssertions.FromClientIP.cs
- src/WireMock.Net.AwesomeAssertions/Assertions/WireMockAssertions.UsingMethod.cs
- src/WireMock.Net.AwesomeAssertions/Assertions/WireMockAssertions.WithBody.cs
- src/WireMock.Net.AwesomeAssertions/Assertions/WireMockAssertions.WithHeader.cs
- src/WireMock.Net.AwesomeAssertions/Assertions/WireMockAssertions.WithProxy.cs
- src/WireMock.Net.AwesomeAssertions/Assertions/WireMockAssertions.cs
- src/WireMock.Net.AwesomeAssertions/Assertions/WireMockReceivedAssertions.cs
- src/WireMock.Net.AwesomeAssertions/Extensions/WireMockExtensions.cs
- src/WireMock.Net.AwesomeAssertions/Usings.cs
- src/WireMock.Net.AwesomeAssertions/WireMock.Net.AwesomeAssertions.csproj
Adding new project for AwesomeAssertions support after FluentAssertions license change (as proposed in #1243).
> feat(awesome-assertions): Added new project WireMock.Net.AwesomeAssertions
